spring:
  application:
    name: TaskManagerEurekaServer-1
 
server:
  port: 8761
 
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    enabled: false
  server:
    enableSelfPreservation: false

